# Site settings
title: KIAPI MSIT22 OpenLabs
email: your-email@domain.com
url: https://kiapi-knpa-10.github.io
description: |
  [자율주행기술개발혁신사업]<br><br>
  클라우드 기반 자율주행 차량 오류 및 한계 상황<br>
  지능형 원격지원 기술 개발<br><br><br><br>

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: KIAPI MSIT22 OpenLabs

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
